config/routes.rb
Rails.application.routes.draw do
  get 'dev/index'
root 'dev#index'
  get 'status/GoCDStatus'
  get 'status/GoCDUpdate'
  get 'status/organization'
  get 'status/verification'
  get 'status/waiting'
 get 'bitbuc/prstatus'
 Rails.application.routes.draw do
      devise_for :devop_users, controllers: {
        sessions: 'devopuser/sessions'
      }
    end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Devops PMS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style media="screen">
    .usericon
{
font-size:29px;
color:white;
margin-right:15px;
}
    </style>
  </head>

  <body>

    <div class="menubar">
      <div id="userpanel">
        <ul>
          <li>
        <i  class="fa fa-user-circle usericon"></i>
            <ul>
              <li><%= link_to "Profile",status_waiting_path %></li>
              <li> <%= link_to('logout', destroy_devop_user_session_path, method: :delete) %></li>
            </ul>
          </li>
        </ul>
      </div>
      <h4 class="heading">DevOps PMS</h4>
    </div>
    <div class="ro">
    <div id="divMenu">
        <ul>
            <li><%= link_to "Home",dev_index_path %>
                </li>
            <li><a href="#">Red Mine</a>
                    <ul>
                <li><%= link_to "Unlogged Users",  status_verification_path%></li>
                <li><%= link_to "Verification Issues" ,status_verification_path  %></li>
                <li><%= link_to "Waiting Issues" ,status_waiting_path %></li>
            </ul></li>
            <li><a href="#">GoCD</a>
                    <ul>
                      <li ><%= link_to "Build status" ,status_GoCDStatus_path %><li>
                      <li ><%=link_to "Build Update" ,status_GoCDUpdate_path %><li>
            </ul></li>
            <li><a href="#">Bit Bucket</a>
            <ul>
              <li><%= link_to "PR Request", bitbuc_prstatus_path%></li>
            </ul></li>
            <li><a href="#">Holidays</a>
                    <ul>
                      <li><%= link_to "Organization", status_organization_path%></li>
                      <li><%= link_to "Employee", status_organization_path %></li>
            </ul></li>
            <li><a href="#">Settings</a></li>
        </ul>
      </div>

    <%= yield %>
  </div>
    <footer class="footer">
    <div>
    <p>copyright<i class="fa fa-copyright"></i>appranix.com</p>
    </div>
    </footer>

  </body>
</html>

app/views/layouts/first.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Devops PMS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script type="text/javascript" src="script.js"></script>

  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style media="screen">
    .usericon
{
font-size:29px;
color:white;
margin-right:15px;
}
    </style>
  </head>

  <body>

    <div class="menubar">
      <h4 class="heading">DevOps PMS</h4>
    </div>
    <div class="ro">

    <%= yield %>
  </div>
  <footer class="footerlogin">
  <div>
  <p>copyright<i class="fa fa-copyright"></i>appranix.com</p>
  </div>
  </footer>

  </body>
</html>